### ISSUE TITLE
ImageDataset

### ISSUE THREAD

**Issue by sahithi403** [PriyankaChaganti/traffic_sign_svm#20]
In data_set.py,
1.create a class ImageDataset
2. __init__ function should have a function parameter 'hog'.  
__init__ function should have 'data', 'class_ids' and 'hog' as instance attributes. The default values should be an empty list, empty list and False respectively
3. Add a method 'add_image' to the class with function parameters 'data_sets_path', 'data_set', and 'annotation'. The function should get the filename and class_id from the annotation. The function should read the corresponding hog3 feature file using 'get_hog_features' from task #18. The function should add the class_id and feature_vector to instance attribute data using the 'add_row' method from step 4
4.  Add a method 'add_row' to the class with function parameters class_id and 'feature_vector'. The function should create a dictionary with keys 'class_id' and 'feature_vector' and append the dictionary to the class attribute data. 
5. Add a method 'shuffle' to the class. The method should shuffle instance attribute data using numpy.random.shuffle

**Comment by PriyankaChaganti** [comment]
There is previously created _init_ method in ImageDataset....Do they refer to the same function??
Currently coding in _init_ method

**Comment by PriyankaChaganti** [comment]
did not complete 3(did not know how to read required info from annotations file)

**Comment by sahithi403** [comment]
A class would only one init method
